server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  #定义名称，用于binding整合
          type: rabbit  #消息组件类型
          environment: #环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json
          binder: defaultRabbit #要绑定消息服务的具体设置
          group: zhanghao1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳时间间隔
    lease-expiration-duration-in-seconds: 5 #超过五秒时间间隔，默认90
    instance-id: receive-8803.com  #在信息列表显示主机名称
    prefer-ip-address: true #访问路径变为ip地址



