server:
  port: 2002

spring:
  application:
    name: seata-storage-service

  cloud:
    alibaba:
      seata:
        #        seata事物组名称要和seata server中的名称对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        #        server-addr: 192.168.199.208:1111  #         换成nginx转发的nacos集群
        server-addr: localhost:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: zhanghao
    type: com.alibaba.druid.pool.DruidDataSource


#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    io:
      seata: info
