server:
  port: 7002



eureka:
  instance:
    hostname: eureka7002.com #Eureka服务的实例名称
  client:
    register-with-eureka: false  #不向本机注册中心注册自己
    #    false表示自己端就是服务中心，我只需要维护服务实例，不需要去提供检索
    fetch-registry: false

    #    与eureka交互的地址查询服务和注册服务都需要这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/