server:
  port: 9001


spring:
  application:
    name: nacos-payment-provider

#nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

