server:
  port: 83

spring:
  application:
    name: nacos-order-consumer

  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

#消费者将要去访问的微服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider