
server:
  port: 80

eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka    #集群板
    register-with-eureka: false

ribbon:
#  建立网络连接所用时间，适用于网络正常情况
  ReadTimeout: 5000
#  建立连接后从服务器读取可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
#    feign日志以什么级别监控哪个接口
    com.zhanghao.springcloud.service.PaymentFeignService: debug